### ISSUE TITLE
Running the .jar

### ISSUE THREAD

**Issue by PrimeEdits** [Gnar-Team/Gnar-bot#26]
i get this error when i run the .jar file.

Exception in thread "main" java.lang.IllegalStateException: Bot token can't be null or blank.
        at xyz.gnarbot.gnar.Credentials.<init>(Credentials.kt:26)
        at xyz.gnarbot.gnar.BotLoader.main(BotLoader.java:15)

**Comment by Xevryll** [comment]
We do not provide support when it comes to self-hosting Gnar, sorry.
